[module]
name = "botwsavs"
title-id = 0x01007ef00011e000

# make configuration
[build]
sources = [
    "src",
    "libs/botw-symbols/src",
]
includes = [
    "src",
    "libs/botw/src",
    "libs/botw/lib/agl/include",
    "libs/botw/lib/gsys/include",
    "libs/botw-symbols/include",
    "libs/sead/include",
    "libs/nnheaders/include",
]
ldscripts = [
    "libs/botw-symbols/ld/ld160.ld",
    "libs/botw-symbols/ld/toolkit160.ld",
]

[build.flags]
c = [
    "<default>",
    "-DNNSDK",
    "-DSWITCH",
    "-D__SWITCH__",
    "-DNN_SDK_MAJOR=7",
    "-DNN_SDK_MINOR=3",
    "-DNN_SDK_PATCH=2",
    "-DNN_WARE_MAJOR=7",
    "-DNN_WARE_MINOR=3",
    "-DNN_WARE_PATCH=2",
    "-DBOTW_VERSION=160",
]
cxx = [
    "<default>",
    "-Wno-invalid-offsetof",
]

[build.profiles.debug.flags]
c = [
    "-DBOTWTOOLKIT_TCP_SEND",
]

[check]
ignore = [
    # ".data",
    # ".text",
]
symbols = [
    "libs/botw-symbols/symbols/160/main.syms",
    "libs/botw-symbols/symbols/160/rtld.syms",
    "libs/botw-symbols/symbols/160/sdk.syms",
    "libs/botw-symbols/symbols/160/subsdk0.syms",
]
