version: '3'

env:
  # can be overriden in .env
  # CONSOLE_ADDR: 192.168.0.161:5000
  # DEBUG_ADDR: 192.168.0.161:5001
dotenv: [".env"]

includes:
  symbols:
    aliases: [sym]
    taskfile: libs/botw-symbols
    dir: libs/botw-symbols

tasks:
  build:
    aliases: [b]
    desc: Build the mod
    cmds:
      - megaton build -p debug

  check:
    desc: Check code for errors
    cmds:
      - clang-format -n -Werror $(find src -name '*.cpp' -o -name '*.hpp')

  fix:
    desc: Fix errors in code
    cmds:
      - clang-format -i $(find src -name '*.cpp' -o -name '*.hpp')

  package:
    desc: Package the build for release
    vars:
      VERSION: "SS2.4"
      MOD_DIR: "target/package/mods/The Legend of Zelda - Breath of the Wild/Save State/contents/01007EF00011E000"
    cmds:
      - megaton build -p none
      - rm -rf target/package/mods
      - mkdir -p "{{.MOD_DIR}}/exefs"
      - mkdir -p "{{.MOD_DIR}}/romfs/System"
      - cp target/megaton/none/main.npdm "{{.MOD_DIR}}/exefs/main.npdm"
      - cp target/megaton/none/botwsavs.nso "{{.MOD_DIR}}/exefs/subsdk9"
      - mkdir -p target/package/botwsavs
      - echo "" > target/package/botwsavs/latest.txt
      - echo -n "1.6.0-{{.VERSION}}" > "{{.MOD_DIR}}/romfs/System/Version.txt"
      - cd target/package && zip -r ../botw-save-state-{{.VERSION}}.zip .

  upload:
    aliases: [u]
    desc: Upload build to console via FTP
    cmds:
    - lftp $CONSOLE_ADDR < scripts/lftp-upload.sh

  download:
    desc: Download logs and data from console
    cmds:
    - mkdir -p target/crash_reports/dumps
    - lftp $CONSOLE_ADDR < scripts/lftp-download.sh

  debug:
    cmds:
    - python libs/botw-symbols/tcp-client.py $DEBUG_ADDR
