blank = 0;
_ZN8botwsavs3mem7KingPtr10MainMemoryE = 0x0 - 0x3483000; /* MainMemory */
_ZN8botwsavs3mem7KingPtr22sControllerMgrInstanceE = 0x2CBF658 - 0x3483000; /* sControllerMgrInstance */
_ZN8botwsavs3mem7KingPtr25ShowInfoOverlayWithStringEmPKv = 0x1238680 - 0x3483000; /* ShowInfoOverlayWithString */
_ZN8botwsavs3mem7KingPtr16GetMessageStringEPvS2_S2_ = 0x123DEA0 - 0x3483000; /* GetMessageString */
_ZN5uking2ui16PauseMenuDataMgr9sInstanceE = 0x02CA6D50 - 0x3483000; /* PauseMenu */
